Error: Python: Traceback (most recent call last):
  File "\Text", line 12, in <module>
  File "\Text", line 12, in <listcomp>
TypeError: list indices must be integers or slices, not str
